language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.10
  - DJANGO_VERSION=1.9.4
script: "python manage.py test batchform"
install:
  - pip install Django==$DJANGO_VERSION --quiet --use-mirrors
  - python setup.py --quiet install
notifications:
  email: false
  irc: "irc.freenode.org#XelNext"

